// Help content data for the integrated help system
// All help articles, tooltips, tours, and suggestions are defined here.

// ─── Types ──────────────────────────────────────────────────────────────────

export interface HelpTooltipData {
  id: string;
  title: string;
  description: string;
  shortcut?: string;
  learnMoreId?: string;
}

export interface HelpArticle {
  id: string;
  title: string;
  category: string;
  tags: string[];
  content: string; // Markdown
  relatedArticles: string[];
  examples?: string[];
  lastUpdated: string;
}

export interface HelpCategory {
  id: string;
  title: string;
  icon: string; // Lucide icon name
  description: string;
  articles: string[];
}

export interface TourStep {
  targetSelector: string;
  title: string;
  content: string;
  placement: 'top' | 'bottom' | 'left' | 'right' | 'center';
  action?: 'click' | 'type' | 'wait';
  actionHint?: string;
}

export interface Tour {
  id: string;
  name: string;
  description: string;
  steps: TourStep[];
}

export interface SmartSuggestionDef {
  id: string;
  event: string;
  message: string;
  actionLabel?: string;
  actionType?: 'tour' | 'article' | 'command';
  actionTarget?: string;
}

// ─── Tooltips ───────────────────────────────────────────────────────────────

export const tooltips: Record<string, HelpTooltipData> = {
  'header.agent-loop': {
    id: 'header.agent-loop',
    title: 'Agent Loop Controls',
    description: 'Start, pause, or stop the autonomous agent loop that runs in the background to work on your project.',
    shortcut: '⌘⇧L',
    learnMoreId: 'agent-loop',
  },
  'header.palette': {
    id: 'header.palette',
    title: 'Command Palette',
    description: 'Search and execute any action. Type to filter commands.',
    shortcut: '⌘⇧P',
    learnMoreId: 'getting-started.commands',
  },
  'header.settings': {
    id: 'header.settings',
    title: 'Settings',
    description: 'Configure AI providers, model routing, plugins, and more.',
    shortcut: '⌘,',
    learnMoreId: 'configuration.overview',
  },
  'header.workspace': {
    id: 'header.workspace',
    title: 'Workspace',
    description: 'Your current working directory. Click to change which project Oboto works on.',
    learnMoreId: 'getting-started.workspace',
  },
  'header.connection': {
    id: 'header.connection',
    title: 'Connection Status',
    description: 'Shows whether the UI is connected to the Oboto server via WebSocket.',
  },
  'header.conversations': {
    id: 'header.conversations',
    title: 'Conversations',
    description: 'Switch between multiple parallel conversations. Each conversation maintains its own context.',
    learnMoreId: 'getting-started.conversations',
  },
  'sidebar.project-status': {
    id: 'sidebar.project-status',
    title: 'Project Status',
    description: 'Overview of your project including manifest features, phases, and current development status.',
    learnMoreId: 'tools.structured-dev',
  },
  'sidebar.surfaces': {
    id: 'sidebar.surfaces',
    title: 'Surfaces',
    description: 'Dynamic React dashboards generated by Oboto. Pin them to keep them accessible.',
    learnMoreId: 'surfaces.overview',
  },
  'sidebar.files': {
    id: 'sidebar.files',
    title: 'File Explorer',
    description: 'Browse and open files in your workspace. Click a file to view or edit it.',
    learnMoreId: 'getting-started.workspace',
  },
  'sidebar.skills': {
    id: 'sidebar.skills',
    title: 'Skills',
    description: 'Modular capability extensions. Install skills to give Oboto new abilities.',
    learnMoreId: 'plugins-skills.skills',
  },
  'sidebar.plugins': {
    id: 'sidebar.plugins',
    title: 'Plugins',
    description: 'Extend Oboto with plugins that add UI panels, tools, and integrations.',
    learnMoreId: 'plugins-skills.plugins',
  },
  'chat.input': {
    id: 'chat.input',
    title: 'Chat Input',
    description: 'Type messages, questions, or commands. You can ask Oboto to write code, search files, run commands, and more.',
    shortcut: '⌘⇧I',
    learnMoreId: 'getting-started.chat',
  },
  'chat.interrupt': {
    id: 'chat.interrupt',
    title: 'Interrupt',
    description: 'Stop the current AI response in progress.',
    shortcut: 'Escape',
  },
};

// ─── Placeholder Hints ─────────────────────────────────────────────────────

export const placeholderHints: string[] = [
  'try: "create a REST API for users"',
  'try: "search for TODO comments in my code"',
  'try: "generate a dashboard surface"',
  'try: "run my test suite"',
  'try: "explain this codebase"',
  'try: "refactor the database layer"',
  'try: "what tools do you have?"',
  'try: /help for all commands',
  'try: "set up CI/CD for this project"',
  'try: "create a new React component"',
  'try: "find and fix bugs in src/"',
  'try: "write tests for the API"',
];

// ─── Categories ─────────────────────────────────────────────────────────────

export const helpCategories: HelpCategory[] = [
  {
    id: 'getting-started',
    title: 'Getting Started',
    icon: 'BookOpen',
    description: 'Learn the basics of using Oboto',
    articles: ['getting-started.overview', 'getting-started.chat', 'getting-started.commands', 'getting-started.workspace', 'getting-started.conversations'],
  },
  {
    id: 'tools',
    title: 'Tools Reference',
    icon: 'Wrench',
    description: 'All 50+ built-in tools and capabilities',
    articles: ['tools.overview', 'tools.file-ops', 'tools.shell', 'tools.browser', 'tools.image', 'tools.math', 'tools.web', 'tools.structured-dev'],
  },
  {
    id: 'surfaces',
    title: 'Surfaces & Dashboards',
    icon: 'LayoutDashboard',
    description: 'Create dynamic UI dashboards',
    articles: ['surfaces.overview', 'surfaces.creating', 'surfaces.components', 'surfaces.pinning'],
  },
  {
    id: 'agent-loop',
    title: 'Agent Loop & Automation',
    icon: 'Bot',
    description: 'Autonomous agent and background tasks',
    articles: ['agent-loop', 'agent-loop.background-tasks', 'agent-loop.scheduling'],
  },
  {
    id: 'plugins-skills',
    title: 'Plugins & Skills',
    icon: 'Puzzle',
    description: 'Extend Oboto with modular capabilities',
    articles: ['plugins-skills.plugins', 'plugins-skills.skills', 'plugins-skills.mcp'],
  },
  {
    id: 'configuration',
    title: 'Configuration',
    icon: 'Settings',
    description: 'AI providers, model routing, and settings',
    articles: ['configuration.overview', 'configuration.providers', 'configuration.routing', 'configuration.secrets', 'configuration.openclaw'],
  },
  {
    id: 'shortcuts',
    title: 'Keyboard Shortcuts',
    icon: 'Keyboard',
    description: 'Navigate Oboto efficiently',
    articles: ['shortcuts.all'],
  },
  {
    id: 'tours',
    title: 'Interactive Tours',
    icon: 'GraduationCap',
    description: 'Guided walkthroughs of features',
    articles: ['tours.available'],
  },
];

// ─── Articles ───────────────────────────────────────────────────────────────

export const helpArticles: Record<string, HelpArticle> = {
  'getting-started.overview': {
    id: 'getting-started.overview',
    title: 'Welcome to Oboto',
    category: 'getting-started',
    tags: ['intro', 'overview', 'basics', 'welcome', 'start'],
    content: `# Welcome to Oboto

Oboto is an AI-powered assistant that helps you with software development, project management, automation, and more.

## What Can Oboto Do?

- **Write & edit code** — Ask Oboto to create files, refactor code, or implement features
- **Run commands** — Execute shell commands, run tests, manage processes
- **Browse & automate** — Control a browser, take screenshots, interact with web pages
- **Create dashboards** — Generate dynamic React "Surfaces" to visualize data
- **Work autonomously** — Run the Agent Loop to have Oboto continuously work on tasks
- **Manage projects** — Track features, phases, and dependencies via structured development

## Getting Help

- Press **⌘/** to open this help panel anytime
- Press **⌘⇧P** to search for any command
- Type **/help** in the chat for quick guidance
- Ask Oboto directly: *"What can you do?"*`,
    relatedArticles: ['getting-started.chat', 'getting-started.commands', 'tools.overview'],
    examples: ['What can you do?', 'Help me get started', 'Show me what tools you have'],
    lastUpdated: '2026-02-27',
  },

  'getting-started.chat': {
    id: 'getting-started.chat',
    title: 'Using the Chat',
    category: 'getting-started',
    tags: ['chat', 'message', 'input', 'conversation', 'talk'],
    content: `# Using the Chat

The chat is your primary interface with Oboto. Type natural language messages to interact.

## Tips

- **Be specific** — "Create a User model with name and email fields" works better than "create a model"
- **Provide context** — Mention file names, paths, or technologies
- **Ask questions** — Oboto can explain code, suggest approaches, or analyze your project
- **Use slash commands** — Type \`/\` to see available commands

## Attachments

You can drag and drop files into the chat to share them with Oboto. Images are analyzed visually.

## Multi-turn Conversations

Oboto remembers your conversation context. You can refer back to earlier messages and build on previous work.

## Multiple Conversations

Use the conversation switcher in the header to create multiple parallel conversations. Each maintains its own context and history.`,
    relatedArticles: ['getting-started.commands', 'getting-started.conversations'],
    examples: ['Create a new React component called UserCard', 'Explain the code in src/main.mjs', 'What did we discuss earlier?'],
    lastUpdated: '2026-02-27',
  },

  'getting-started.commands': {
    id: 'getting-started.commands',
    title: 'Commands & Palette',
    category: 'getting-started',
    tags: ['commands', 'palette', 'actions', 'shortcuts'],
    content: `# Commands & Palette

## Command Palette

Press **⌘⇧P** to open the command palette. This is the fastest way to access any action in Oboto.

Type to filter commands, use arrow keys to navigate, and press Enter to execute.

## Available Commands

The palette includes commands for:
- Opening settings, secrets vault, and help
- Managing surfaces and conversations
- Controlling the agent loop
- Switching themes
- File operations
- And more

## Slash Commands

In the chat input, type \`/\` followed by a command:
- \`/help\` — Quick help reference
- \`/surface\` — Create a new surface
- \`/clear\` — Clear the conversation`,
    relatedArticles: ['getting-started.chat', 'shortcuts.all'],
    lastUpdated: '2026-02-27',
  },

  'getting-started.workspace': {
    id: 'getting-started.workspace',
    title: 'Workspace Management',
    category: 'getting-started',
    tags: ['workspace', 'directory', 'project', 'folder', 'files'],
    content: `# Workspace Management

Your workspace is the directory Oboto operates in. All file operations, searches, and commands execute relative to this directory.

## Changing Workspace

Click the workspace path in the header to open the directory picker. You can navigate to any directory on your system.

## File Explorer

The sidebar file explorer shows your workspace contents. Click a file to view it in the editor tab.

## Multiple Workspaces

You can spawn workspace tasks that operate on different directories simultaneously. Use the Task Manager to monitor them.`,
    relatedArticles: ['getting-started.overview', 'tools.file-ops'],
    lastUpdated: '2026-02-27',
  },

  'getting-started.conversations': {
    id: 'getting-started.conversations',
    title: 'Multiple Conversations',
    category: 'getting-started',
    tags: ['conversations', 'parallel', 'multi', 'switch', 'context'],
    content: `# Multiple Conversations

Oboto supports multiple parallel conversations per workspace. Each conversation maintains its own message history and context.

## Creating Conversations

Click the conversation name in the header to open the switcher. Click "New Conversation" to create one.

## Switching

Click any conversation name to switch to it. Your messages and context are preserved.

## Use Cases

- Work on frontend and backend in separate conversations
- Keep a "research" conversation alongside an "implementation" one
- Test different approaches in isolated contexts`,
    relatedArticles: ['getting-started.chat'],
    lastUpdated: '2026-02-27',
  },

  'tools.overview': {
    id: 'tools.overview',
    title: 'Tools Overview',
    category: 'tools',
    tags: ['tools', 'capabilities', 'features', 'what can you do'],
    content: `# Tools Overview

Oboto has **50+ built-in tools** across multiple categories. Tools are automatically selected based on your request — you don't need to specify which tool to use.

## Categories

| Category | Description |
|----------|-------------|
| **File Operations** | Read, write, search, diff files |
| **Shell** | Execute terminal commands |
| **Browser** | Navigate, click, type, screenshot via Puppeteer |
| **Desktop** | Mouse, keyboard, screen automation |
| **Image** | Generate, edit, analyze images |
| **Math** | Evaluate expressions, symbolic computation |
| **Web** | HTTP requests, web search |
| **Structured Dev** | Manifest, flow management, bootstrapping |
| **MCP** | Model Context Protocol integration |
| **Surfaces** | Create/update dynamic dashboards |
| **Async Tasks** | Background task management |
| **Skills** | Invoke installed skills |

## How It Works

When you make a request, Oboto's AI determines which tools are needed and executes them. Some tools require confirmation before execution (file writes, shell commands).`,
    relatedArticles: ['tools.file-ops', 'tools.shell', 'tools.browser'],
    examples: ['What tools do you have?', 'List all your capabilities'],
    lastUpdated: '2026-02-27',
  },

  'tools.file-ops': {
    id: 'tools.file-ops',
    title: 'File Operations',
    category: 'tools',
    tags: ['files', 'read', 'write', 'search', 'diff', 'create', 'delete'],
    content: `# File Operations

## Reading Files

Ask Oboto to read any file in your workspace. It can handle text files, JSON, code, and more.

## Writing Files

Oboto can create new files or modify existing ones. File writes require your approval before executing.

## Searching

Search across your codebase by content, filename, or pattern. Supports regex.

## Examples

- "Read package.json"
- "Create a new file called utils.ts with a debounce function"
- "Search for all TODO comments in src/"
- "Show me the diff between these two files"`,
    relatedArticles: ['tools.overview', 'tools.shell'],
    examples: ['Read the README', 'Create a new config file', 'Search for console.log in src/'],
    lastUpdated: '2026-02-27',
  },

  'tools.shell': {
    id: 'tools.shell',
    title: 'Shell Commands',
    category: 'tools',
    tags: ['shell', 'terminal', 'command', 'execute', 'run', 'npm', 'git'],
    content: `# Shell Commands

Oboto can execute shell commands in your workspace directory. Commands require approval before running.

## Common Uses

- Running tests: \`npm test\`
- Installing packages: \`npm install express\`
- Git operations: \`git status\`, \`git diff\`
- Building projects: \`npm run build\`

## Interactive Terminal

The Guake-style terminal (press **⌘\`**) gives you direct terminal access alongside the chat.

## Safety

Destructive commands (rm, format, etc.) require explicit approval and show a warning.`,
    relatedArticles: ['tools.overview', 'tools.file-ops'],
    examples: ['Run npm test', 'Show git status', 'Install express'],
    lastUpdated: '2026-02-27',
  },

  'tools.browser': {
    id: 'tools.browser',
    title: 'Browser Automation',
    category: 'tools',
    tags: ['browser', 'puppeteer', 'chrome', 'screenshot', 'navigate', 'click', 'web'],
    content: `# Browser Automation

Oboto can control a headless Chrome browser via Puppeteer, or interact with your actual Chrome browser via the Chrome Extension.

## Puppeteer (Built-in)

- Navigate to URLs
- Click elements, fill forms
- Take screenshots
- Extract page content

## Chrome Extension

Install the Chrome Extension for enhanced browser control:
- Tab management
- DOM interaction
- Cookie/storage access
- Real-time event streaming

## Examples

- "Open localhost:3000 and take a screenshot"
- "Navigate to the login page and fill in the form"
- "Check if the homepage loads correctly"`,
    relatedArticles: ['tools.overview'],
    examples: ['Take a screenshot of localhost:3000', 'Navigate to google.com'],
    lastUpdated: '2026-02-27',
  },

  'tools.image': {
    id: 'tools.image',
    title: 'Image Tools',
    category: 'tools',
    tags: ['image', 'generate', 'edit', 'analyze', 'picture', 'photo'],
    content: `# Image Tools

Oboto can generate, edit, and analyze images using AI.

## Generation

Create images from text descriptions using AI image generation.

## Analysis

Drop an image into the chat and Oboto will analyze it visually — useful for UI reviews, debugging visual issues, or extracting information.

## Editing

Basic image manipulation including resize, crop, and format conversion via Sharp.`,
    relatedArticles: ['tools.overview'],
    examples: ['Generate an icon for my app', 'Analyze this screenshot'],
    lastUpdated: '2026-02-27',
  },

  'tools.math': {
    id: 'tools.math',
    title: 'Math & Computation',
    category: 'tools',
    tags: ['math', 'calculate', 'evaluate', 'expression', 'wolfram'],
    content: `# Math & Computation

Oboto includes a Wolfram-style computation engine powered by mathjs.

## Capabilities

- Evaluate mathematical expressions
- Symbolic algebra
- Unit conversions
- Statistical functions
- Matrix operations`,
    relatedArticles: ['tools.overview'],
    examples: ['Calculate the factorial of 20', 'Convert 100 miles to kilometers'],
    lastUpdated: '2026-02-27',
  },

  'tools.web': {
    id: 'tools.web',
    title: 'Web Requests & Search',
    category: 'tools',
    tags: ['web', 'fetch', 'http', 'search', 'api', 'request', 'google'],
    content: `# Web Requests & Search

## HTTP Requests

Oboto can make HTTP requests to any URL — useful for testing APIs, fetching data, or checking endpoints.

## Web Search

Search the web for information using the built-in search integration. Results include snippets and URLs.`,
    relatedArticles: ['tools.overview', 'tools.browser'],
    examples: ['Search for React best practices', 'Fetch the API at https://api.example.com/status'],
    lastUpdated: '2026-02-27',
  },

  'tools.structured-dev': {
    id: 'tools.structured-dev',
    title: 'Structured Development',
    category: 'tools',
    tags: ['manifest', 'SYSTEM_MAP', 'architecture', 'project', 'bootstrap', 'scaffold'],
    content: `# Structured Development

Oboto's structured development system enforces architectural discipline through a "Living Manifest" (SYSTEM_MAP.md).

## Features

- **Project Bootstrapping** — Scaffold new projects with best-practice structure
- **Manifest Management** — Track features, phases, and dependencies
- **Flow Management** — Manage development workflows
- **C4 Visualization** — Generate architecture diagrams
- **CI/CD Architect** — Design deployment pipelines

## How It Works

The SYSTEM_MAP.md file tracks global invariants, feature registry, dependencies, and state snapshots. Oboto ensures changes align with this architecture.`,
    relatedArticles: ['tools.overview'],
    examples: ['Bootstrap a new Express project', 'Show the current project manifest'],
    lastUpdated: '2026-02-27',
  },

  'surfaces.overview': {
    id: 'surfaces.overview',
    title: 'What Are Surfaces?',
    category: 'surfaces',
    tags: ['surfaces', 'dashboard', 'ui', 'dynamic', 'react', 'components'],
    content: `# What Are Surfaces?

Surfaces are dynamic React dashboards that Oboto generates on the fly. They can display data, charts, controls, and interactive elements.

## Key Concepts

- **Surfaces** are named containers that hold UI components
- **Components** are React elements rendered inside surfaces
- **Surface Kit** provides pre-built primitives (charts, tables, buttons, etc.)
- Surfaces persist across sessions and can be pinned for quick access

## Use Cases

- Project status dashboards
- Data visualization
- Custom control panels
- Test result displays
- Monitoring dashboards`,
    relatedArticles: ['surfaces.creating', 'surfaces.components', 'surfaces.pinning'],
    examples: ['Create a dashboard showing project status', 'Make a surface with a bar chart'],
    lastUpdated: '2026-02-27',
  },

  'surfaces.creating': {
    id: 'surfaces.creating',
    title: 'Creating Surfaces',
    category: 'surfaces',
    tags: ['create', 'surface', 'new', 'make', 'dashboard'],
    content: `# Creating Surfaces

Ask Oboto to create a surface by describing what you want to see.

## Examples

- "Create a dashboard showing my project's test results"
- "Make a surface with CPU and memory usage charts"
- "Generate a kanban board for my tasks"

## Surface Kit Components

Surfaces can use any component from the Surface Kit:
- Charts: Line, Bar, Area, Pie, Sparkline
- Data: Table, Badge, Progress, Avatar
- Layout: Card, Stack, ScrollArea
- Inputs: Button, Input, Select, Switch
- Feedback: Alert, Toast
- Navigation: Tabs, Accordion

## Tips

- Be descriptive about what data you want to display
- Surfaces auto-update when Oboto modifies them
- You can ask Oboto to modify an existing surface`,
    relatedArticles: ['surfaces.overview', 'surfaces.components'],
    examples: ['Create a dashboard for this project', 'Add a chart to the monitoring surface'],
    lastUpdated: '2026-02-27',
  },

  'surfaces.components': {
    id: 'surfaces.components',
    title: 'Surface Kit Components',
    category: 'surfaces',
    tags: ['components', 'chart', 'table', 'button', 'card', 'surface-kit'],
    content: `# Surface Kit Components

The Surface Kit provides a library of pre-built React components for use in surfaces.

## Charts
- **LineChart** — Time series, trends
- **BarChart** — Comparisons
- **AreaChart** — Volume, cumulative data
- **PieChart** — Proportions
- **Sparkline** — Inline mini charts

## Data Display
- **Table** — Sortable, filterable tables
- **Badge** — Status indicators
- **Progress** — Progress bars
- **Avatar** — User/entity icons

## Layout
- **Card** — Content containers
- **Stack** — Vertical/horizontal layouts
- **ScrollArea** — Scrollable regions
- **Separator** — Visual dividers

## Inputs
- **Button** — Actions
- **Input** — Text fields
- **Select** — Dropdowns
- **Switch** — Toggles
- **Checkbox** — Multi-select
- **Slider** — Range inputs
- **TextArea** — Multi-line text`,
    relatedArticles: ['surfaces.overview', 'surfaces.creating'],
    lastUpdated: '2026-02-27',
  },

  'surfaces.pinning': {
    id: 'surfaces.pinning',
    title: 'Pinning & Managing Surfaces',
    category: 'surfaces',
    tags: ['pin', 'manage', 'rename', 'delete', 'duplicate', 'surface'],
    content: `# Pinning & Managing Surfaces

## Pinning

Pin surfaces to keep them at the top of the sidebar for quick access. Right-click a surface and select "Pin."

## Managing

Right-click any surface in the sidebar for options:
- **Rename** — Change the surface name
- **Duplicate** — Create a copy
- **Delete** — Remove the surface
- **View Source** — See the generated React code`,
    relatedArticles: ['surfaces.overview'],
    lastUpdated: '2026-02-27',
  },

  'agent-loop': {
    id: 'agent-loop',
    title: 'Agent Loop',
    category: 'agent-loop',
    tags: ['agent', 'loop', 'autonomous', 'auto', 'background', 'continuous'],
    content: `# Agent Loop

The Agent Loop lets Oboto work autonomously in the background, continuously analyzing and improving your project.

## Controls

Use the agent loop controls in the header:
- **Play** — Start the loop
- **Pause** — Temporarily pause
- **Stop** — End the loop

## How It Works

1. Oboto analyzes your project state
2. Identifies tasks, issues, or improvements
3. Takes action (with your approval settings)
4. Reports findings back to you
5. Repeats at the configured interval

## Configuration

Set the loop interval in the agent loop controls dropdown. Shorter intervals = more frequent checks.

## Safety

The agent loop respects your confirmation settings. Destructive actions always require approval.`,
    relatedArticles: ['agent-loop.background-tasks', 'agent-loop.scheduling'],
    examples: ['Start the agent loop', 'Have Oboto continuously review my code'],
    lastUpdated: '2026-02-27',
  },

  'agent-loop.background-tasks': {
    id: 'agent-loop.background-tasks',
    title: 'Background Tasks',
    category: 'agent-loop',
    tags: ['background', 'task', 'async', 'parallel', 'spawn'],
    content: `# Background Tasks

Oboto can run tasks in the background while you continue working.

## Spawning Tasks

Ask Oboto to run something in the background:
- "Run the test suite in the background"
- "Analyze the codebase while I work"

## Task Manager

Open the Task Manager (sidebar or command palette) to see all running tasks, their status, and results.

## Workspace Tasks

Spawn tasks that operate on different directories, enabling parallel work across projects.`,
    relatedArticles: ['agent-loop'],
    examples: ['Run tests in the background', 'Spawn a task to analyze code quality'],
    lastUpdated: '2026-02-27',
  },

  'agent-loop.scheduling': {
    id: 'agent-loop.scheduling',
    title: 'Scheduling & Recurring Tasks',
    category: 'agent-loop',
    tags: ['schedule', 'recurring', 'cron', 'timer', 'repeat'],
    content: `# Scheduling & Recurring Tasks

Set up tasks to run at specific intervals or times.

## Examples

- "Run tests every 30 minutes"
- "Check for dependency updates daily"
- "Monitor the API endpoint every 5 minutes"

## Management

View and manage scheduled tasks in the Task Manager panel.`,
    relatedArticles: ['agent-loop', 'agent-loop.background-tasks'],
    lastUpdated: '2026-02-27',
  },

  'plugins-skills.plugins': {
    id: 'plugins-skills.plugins',
    title: 'Plugins',
    category: 'plugins-skills',
    tags: ['plugins', 'extend', 'install', 'addon', 'extension'],
    content: `# Plugins

Plugins extend Oboto with new capabilities, UI panels, and integrations.

## What Plugins Can Do

- Add new sidebar panels
- Register custom tools
- Provide UI components
- Integrate with external services
- Add settings pages

## Managing Plugins

Go to **Settings → Plugins** to see installed plugins, enable/disable them, and configure their settings.

## Plugin Sidebar

Active plugins may add panels to the sidebar. You can show/hide these using the sidebar toolbar.`,
    relatedArticles: ['plugins-skills.skills', 'plugins-skills.mcp'],
    lastUpdated: '2026-02-27',
  },

  'plugins-skills.skills': {
    id: 'plugins-skills.skills',
    title: 'Skills',
    category: 'plugins-skills',
    tags: ['skills', 'install', 'capability', 'module', 'extend'],
    content: `# Skills

Skills are modular capabilities that extend what Oboto can do. Unlike plugins, skills focus on adding new AI-driven abilities rather than UI components.

## Installing Skills

Go to **Settings → Skills** to browse and install skills from:
- **ClawHub** — The skill marketplace
- **npm** — Install skills from npm packages

## Installed Skills

View your installed skills in the sidebar Skills panel. Each skill has its own documentation (SKILL.md).

## Creating Skills

Skills are defined by a SKILL.md file that describes the skill's capabilities, prompts, and tools.`,
    relatedArticles: ['plugins-skills.plugins'],
    lastUpdated: '2026-02-27',
  },

  'plugins-skills.mcp': {
    id: 'plugins-skills.mcp',
    title: 'MCP Servers',
    category: 'plugins-skills',
    tags: ['mcp', 'model context protocol', 'server', 'integration', 'external tools'],
    content: `# MCP Servers

Oboto supports the Model Context Protocol (MCP) for connecting to external tool servers.

## What Is MCP?

MCP is a standard protocol that lets AI assistants connect to external servers that provide additional tools and resources.

## Connecting

Configure MCP servers in your environment or through the settings. Oboto auto-discovers and registers tools from connected servers.

## Use Cases

- Connect to database management tools
- Integrate with cloud services
- Add domain-specific capabilities`,
    relatedArticles: ['plugins-skills.plugins', 'plugins-skills.skills'],
    lastUpdated: '2026-02-27',
  },

  'configuration.overview': {
    id: 'configuration.overview',
    title: 'Configuration Overview',
    category: 'configuration',
    tags: ['settings', 'config', 'configure', 'setup', 'preferences'],
    content: `# Configuration Overview

Access settings via the gear icon in the header or **⌘,**.

## Settings Tabs

- **General** — Max turns, subagents, setup wizard
- **AI Providers** — Configure LLM providers, models, and routing
- **OpenClaw** — External agent gateway integration
- **Skills** — Install and manage skills
- **Plugins** — Plugin configuration
- **Cloud** — Oboto Cloud sync and collaboration`,
    relatedArticles: ['configuration.providers', 'configuration.routing', 'configuration.secrets'],
    lastUpdated: '2026-02-27',
  },

  'configuration.providers': {
    id: 'configuration.providers',
    title: 'AI Providers',
    category: 'configuration',
    tags: ['provider', 'openai', 'gemini', 'anthropic', 'claude', 'gpt', 'model', 'api key'],
    content: `# AI Providers

Oboto supports multiple AI providers. You can use them simultaneously and route different tasks to different models.

## Supported Providers

- **OpenAI** — GPT-4o, GPT-4, GPT-3.5
- **Google Gemini** — Gemini 2.5 Pro, Flash
- **Anthropic** — Claude 4, Sonnet, Haiku
- **Local** — Run models locally via WebLLM

## Setup

1. Go to **Settings → AI Providers**
2. Enable the provider(s) you want
3. Enter your API key (stored in the encrypted Secrets Vault)
4. Select a default model

## Cloud Provider

If connected to Oboto Cloud, you can also use cloud-hosted models without your own API keys.`,
    relatedArticles: ['configuration.overview', 'configuration.routing', 'configuration.secrets'],
    lastUpdated: '2026-02-27',
  },

  'configuration.routing': {
    id: 'configuration.routing',
    title: 'Model Routing',
    category: 'configuration',
    tags: ['routing', 'model', 'route', 'task', 'cost', 'optimization'],
    content: `# Model Routing

Route specific task types to different AI models for cost and quality optimization.

## Route Categories

| Route | Use Case | Recommended |
|-------|----------|-------------|
| **Agentic** | Tool use, multi-step tasks | Fast model (Flash) |
| **Reasoning High** | Complex analysis, architecture | Best model (Pro) |
| **Reasoning Low** | Simple questions, formatting | Cheap model (Flash) |
| **Summarizer** | Summaries, context compression | Fast model |

## Configuration

Go to **Settings → AI Providers → Model Routing** to configure routes.

## How It Works

Oboto analyzes each request and selects the appropriate route. You can override routing by specifying a model in the chat.`,
    relatedArticles: ['configuration.providers', 'configuration.overview'],
    lastUpdated: '2026-02-27',
  },

  'configuration.secrets': {
    id: 'configuration.secrets',
    title: 'Secrets Vault',
    category: 'configuration',
    tags: ['secrets', 'api key', 'vault', 'encrypted', 'password', 'credentials'],
    content: `# Secrets Vault

API keys and credentials are stored in an AES-256-GCM encrypted vault.

## Accessing the Vault

Open the Secrets Vault via **⌘K** → "Secrets Vault" in the command palette.

## Priority Order

Secrets are resolved in this order:
1. Shell environment variables
2. Vault secrets
3. \`.env\` file
4. Defaults

## Security

- Secrets are encrypted at rest in \`.secrets.enc\`
- Never transmitted in plain text
- Vault is locked with a master password`,
    relatedArticles: ['configuration.providers'],
    lastUpdated: '2026-02-27',
  },

  'configuration.openclaw': {
    id: 'configuration.openclaw',
    title: 'OpenClaw Integration',
    category: 'configuration',
    tags: ['openclaw', 'gateway', 'external', 'agent', 'delegate'],
    content: `# OpenClaw Integration

OpenClaw is an external agent gateway that enables cross-system task delegation.

## Modes

- **External** — Connect to a running OpenClaw gateway
- **Integrated** — Run OpenClaw as an integrated process

## Setup

Go to **Settings → OpenClaw** to configure the connection.

## Use Cases

- Delegate tasks to specialized external agents
- Coordinate work across multiple systems
- Access tools from other agent frameworks`,
    relatedArticles: ['configuration.overview'],
    lastUpdated: '2026-02-27',
  },

  'shortcuts.all': {
    id: 'shortcuts.all',
    title: 'All Keyboard Shortcuts',
    category: 'shortcuts',
    tags: ['keyboard', 'shortcut', 'key', 'hotkey', 'binding'],
    content: `# Keyboard Shortcuts

## General
| Shortcut | Action |
|----------|--------|
| **⌘⇧P** | Command Palette |
| **⌘,** | Settings |
| **⌘/** | Help Panel |
| **⌘⇧/** | Keyboard Shortcuts |
| **Escape** | Close dialog / Interrupt |

## Chat
| Shortcut | Action |
|----------|--------|
| **Enter** | Send message |
| **⇧Enter** | New line |
| **⌘⇧I** | Focus chat input |

## Tabs
| Shortcut | Action |
|----------|--------|
| **⌘W** | Close tab |
| **⌘⇧T** | Reopen last tab |
| **⌘1-9** | Switch to tab N |

## Terminal
| Shortcut | Action |
|----------|--------|
| **⌘\`** | Toggle terminal |

## Navigation
| Shortcut | Action |
|----------|--------|
| **⌘B** | Toggle sidebar |`,
    relatedArticles: ['getting-started.commands'],
    lastUpdated: '2026-02-27',
  },

  'tours.available': {
    id: 'tours.available',
    title: 'Available Tours',
    category: 'tours',
    tags: ['tour', 'walkthrough', 'guide', 'interactive', 'onboarding'],
    content: `# Available Tours

Interactive guided tours walk you through Oboto's features step by step.

## Tours

- **Welcome to Oboto** — A quick overview of the interface (8 steps)
- **Chat Basics** — How to use the chat effectively (5 steps)
- **Dynamic Surfaces** — Creating and managing dashboards (6 steps)
- **Agent Loop** — Setting up autonomous operation (4 steps)
- **Tool Capabilities** — Overview of all tools (7 steps)
- **Configuration Deep Dive** — Mastering settings (6 steps)
- **Keyboard Power User** — Essential shortcuts (5 steps)

Select a tour from the help panel or command palette to start.`,
    relatedArticles: ['getting-started.overview'],
    lastUpdated: '2026-02-27',
  },
};

// ─── Tours ──────────────────────────────────────────────────────────────────

export const tours: Tour[] = [
  {
    id: 'onboarding',
    name: 'Welcome to Oboto',
    description: 'A quick overview of the interface',
    steps: [
      {
        targetSelector: '.chat-input-area, [data-help-id="chat.input"]',
        title: 'Chat Area',
        content: 'This is where you talk to Oboto. Type anything — questions, commands, code requests. Oboto understands natural language.',
        placement: 'top',
      },
      {
        targetSelector: '[data-help-id="header.palette"], [title*="Command Palette"]',
        title: 'Command Palette',
        content: 'Press **⌘⇧P** to open the command palette and search through all available actions.',
        placement: 'bottom',
      },
      {
        targetSelector: 'aside, [data-help-id="sidebar"]',
        title: 'Sidebar',
        content: 'Your project status, file explorer, surfaces, skills, and plugins live here. Panels are draggable and collapsible.',
        placement: 'right',
      },
      {
        targetSelector: '[data-help-id="header.agent-loop"]',
        title: 'Agent Loop',
        content: 'The agent loop lets Oboto work **autonomously** in the background — continuously analyzing and improving your project.',
        placement: 'bottom',
      },
      {
        targetSelector: '[data-help-id="header.workspace"]',
        title: 'Workspace',
        content: 'This shows your current working directory. Click to change which project Oboto operates on.',
        placement: 'bottom',
      },
      {
        targetSelector: '[data-help-id="header.conversations"]',
        title: 'Conversations',
        content: 'Start multiple conversations to work on different tasks in parallel. Each maintains its own context.',
        placement: 'bottom',
      },
      {
        targetSelector: '[data-help-id="header.settings"], [title*="Settings"]',
        title: 'Settings',
        content: 'Configure AI providers, model routing, plugins, OpenClaw, and more.',
        placement: 'bottom',
      },
      {
        targetSelector: '[data-help-id="header.help"]',
        title: 'Help',
        content: 'Press **⌘/** anytime to open the help panel. You can also ask me directly — try "what can you do?"',
        placement: 'bottom',
      },
    ],
  },
  {
    id: 'chat-basics',
    name: 'Chat Basics',
    description: 'How to use the chat effectively',
    steps: [
      {
        targetSelector: '.chat-input-area, [data-help-id="chat.input"]',
        title: 'Natural Language Input',
        content: 'Type anything in natural language. Oboto figures out what tools to use automatically.',
        placement: 'top',
      },
      {
        targetSelector: '.message-list, [data-help-id="chat.messages"]',
        title: 'Message History',
        content: 'Your conversation history appears here. Oboto remembers context from earlier messages.',
        placement: 'right',
      },
      {
        targetSelector: '[data-help-id="chat.input"]',
        title: 'Slash Commands',
        content: 'Type **/** for slash commands like `/help`, `/surface`, and `/clear`.',
        placement: 'top',
      },
      {
        targetSelector: '[data-help-id="chat.input"]',
        title: 'File Attachments',
        content: 'Drag and drop files into the chat to share them with Oboto. Images are analyzed visually.',
        placement: 'top',
      },
      {
        targetSelector: '[data-help-id="header.conversations"]',
        title: 'Multiple Conversations',
        content: 'Create parallel conversations for different tasks. Click the conversation name to switch.',
        placement: 'bottom',
      },
    ],
  },
  {
    id: 'surfaces-intro',
    name: 'Dynamic Surfaces',
    description: 'Creating and managing dashboards',
    steps: [
      {
        targetSelector: '[data-help-id="sidebar.surfaces"]',
        title: 'Surfaces Panel',
        content: 'Surfaces appear here in the sidebar. They are dynamic React dashboards generated by Oboto.',
        placement: 'right',
      },
      {
        targetSelector: '.chat-input-area, [data-help-id="chat.input"]',
        title: 'Creating Surfaces',
        content: 'Ask Oboto to create a surface: "Create a dashboard showing test results" or "Make a chart of API response times".',
        placement: 'top',
      },
      {
        targetSelector: '[data-help-id="sidebar.surfaces"]',
        title: 'Pinning Surfaces',
        content: 'Right-click a surface to pin it, keeping it at the top of the list for quick access.',
        placement: 'right',
      },
      {
        targetSelector: '.tab-bar, [data-help-id="tabs"]',
        title: 'Surface Tabs',
        content: 'When you click a surface, it opens in a tab. You can have multiple surfaces open.',
        placement: 'bottom',
      },
      {
        targetSelector: '.chat-input-area, [data-help-id="chat.input"]',
        title: 'Modifying Surfaces',
        content: 'Ask Oboto to update an existing surface: "Add a pie chart to the monitoring dashboard".',
        placement: 'top',
      },
      {
        targetSelector: '[data-help-id="sidebar.surfaces"]',
        title: 'Managing Surfaces',
        content: 'Right-click for options: rename, duplicate, delete, or view the generated source code.',
        placement: 'right',
      },
    ],
  },
  {
    id: 'agent-loop-tour',
    name: 'Autonomous Agent',
    description: 'Setting up autonomous operation',
    steps: [
      {
        targetSelector: '[data-help-id="header.agent-loop"]',
        title: 'Agent Loop Controls',
        content: 'These controls manage the autonomous agent. **Play** starts it, **Pause** suspends, **Stop** ends the session.',
        placement: 'bottom',
      },
      {
        targetSelector: '[data-help-id="header.agent-loop"]',
        title: 'Loop Interval',
        content: 'Click the dropdown to set how often the agent checks for work. Shorter intervals = more responsive.',
        placement: 'bottom',
      },
      {
        targetSelector: '.chat-input-area, [data-help-id="chat.input"]',
        title: 'Giving Objectives',
        content: 'Before starting the loop, tell Oboto what to work on. It will continuously make progress toward that goal.',
        placement: 'top',
      },
      {
        targetSelector: '.message-list, [data-help-id="chat.messages"]',
        title: 'Progress Reports',
        content: 'The agent reports its actions and findings in the chat. You can interrupt or redirect at any time.',
        placement: 'right',
      },
    ],
  },
];

// ─── Smart Suggestions ──────────────────────────────────────────────────────

export const smartSuggestions: SmartSuggestionDef[] = [
  {
    id: 'first-surface',
    event: 'surface-created',
    message: '💡 Surfaces can be pinned to the sidebar for quick access. Right-click to pin.',
    actionLabel: 'Learn about surfaces',
    actionType: 'article',
    actionTarget: 'surfaces.overview',
  },
  {
    id: 'first-tool-fail',
    event: 'tool-error',
    message: '💡 Some tools need configuration. Check Settings → AI Providers for API keys.',
    actionLabel: 'Open Settings',
    actionType: 'command',
    actionTarget: 'settings',
  },
  {
    id: 'many-messages',
    event: 'message-count-10',
    message: '💡 Press ⌘⇧P for the command palette — the fastest way to access any action.',
    actionLabel: 'View all shortcuts',
    actionType: 'article',
    actionTarget: 'shortcuts.all',
  },
  {
    id: 'no-agent-loop',
    event: 'session-5min',
    message: '💡 The Agent Loop can work autonomously in the background. Try the play button in the header.',
    actionLabel: 'Learn about Agent Loop',
    actionType: 'article',
    actionTarget: 'agent-loop',
  },
];

// ─── Empty State Content ────────────────────────────────────────────────────

export const emptyStates: Record<string, { title: string; description: string; suggestions?: string[] }> = {
  'chat': {
    title: 'Start a conversation',
    description: 'Ask Oboto anything — write code, run commands, search files, or get help.',
    suggestions: [
      'Explain this codebase to me',
      'Create a REST API for user management',
      'Search for TODO comments in src/',
      'What can you do?',
    ],
  },
  'surfaces': {
    title: 'No surfaces yet',
    description: 'Surfaces are dynamic dashboards. Ask Oboto to create one.',
    suggestions: [
      'Create a project status dashboard',
      'Make a chart showing test results',
    ],
  },
  'skills': {
    title: 'No skills installed',
    description: 'Skills extend Oboto with new abilities. Browse available skills in Settings.',
  },
  'files': {
    title: 'No workspace set',
    description: 'Click the workspace path in the header to choose a project directory.',
  },
};
