/**
 * Hello World Plugin — demonstrates all major plugin API capabilities.
 *
 * This is a reference implementation for plugin developers.
 */

import { registerSettingsHandlers } from '../../src/plugins/plugin-settings-handlers.mjs';
import { consoleStyler } from '../../src/ui/console-styler.mjs';

const DEFAULT_SETTINGS = {
  enabled: true,
  welcomeMessage: 'Welcome to the hello-world plugin!',
  greetingEmoji: '👋',
  logChatMessages: true,
};

const SETTINGS_SCHEMA = [
  { key: 'enabled', label: 'Enabled', type: 'boolean', description: 'Enable or disable the hello-world plugin', default: true },
  { key: 'welcomeMessage', label: 'Welcome Message', type: 'text', description: 'Message displayed on activation', default: 'Welcome to the hello-world plugin!' },
  { key: 'greetingEmoji', label: 'Greeting Emoji', type: 'text', description: 'Emoji appended to greetings', default: '👋' },
  { key: 'logChatMessages', label: 'Log Chat Messages', type: 'boolean', description: 'Log incoming chat messages to console', default: true },
];

/**
 * Called when the plugin is activated.
 * @param {import('../../src/plugins/plugin-api.mjs').PluginAPI} api
 */
export async function activate(api) {
    consoleStyler.log('plugin', 'Plugin activated!');

    const { pluginSettings } = await registerSettingsHandlers(
        api, 'hello-world', DEFAULT_SETTINGS, SETTINGS_SCHEMA
    );

    // ── Register a custom tool ──────────────────────────────────────────
    api.tools.register({
        useOriginalName: true,
        name: 'greet',
        description: 'Say hello from the hello-world plugin',
        parameters: {
            type: 'object',
            properties: {
                name: { type: 'string', description: 'Name to greet' }
            },
            required: ['name']
        },
        handler: async (args) => {
            const emoji = pluginSettings.greetingEmoji || '👋';
            const greeting = `Hello, ${args.name}! ${emoji} This greeting was generated by the hello-world plugin.`;
            
            // Emit an event other plugins can listen to
            api.events.emit('greeted', { name: args.name, greeting });
            
            // Store the greeting count
            const count = (await api.storage.get('greetCount')) || 0;
            await api.storage.set('greetCount', count + 1);
            
            return greeting;
        }
    });

    // ── Register a WebSocket handler ────────────────────────────────────
    api.ws.register('ping', async (data, ctx) => {
        ctx.ws.send(JSON.stringify({
            type: 'plugin:hello-world:pong',
            payload: { 
                message: 'Pong from hello-world plugin!',
                timestamp: new Date().toISOString()
            }
        }));
    });

    // ── Listen for system events ────────────────────────────────────────
    api.events.onSystem('chat:message', (data) => {
        if (pluginSettings.logChatMessages) {
            consoleStyler.log('plugin', `Chat message received: ${data?.content?.substring(0, 50)}`);
        }
    });

    consoleStyler.log('plugin', `Initialization complete. Welcome: ${pluginSettings.welcomeMessage}`);
}

/**
 * Called when the plugin is deactivated.
 * @param {import('../../src/plugins/plugin-api.mjs').PluginAPI} api
 */
export async function deactivate(api) {
    consoleStyler.log('plugin', 'Plugin deactivated. Goodbye!');
    // Note: The plugin system automatically cleans up registered tools, WS handlers,
    // and event listeners — no manual cleanup needed here.
}
