/**
 * Hello World Plugin — demonstrates all major plugin API capabilities.
 * 
 * This is a reference implementation for plugin developers.
 */

/**
 * Called when the plugin is activated.
 * @param {import('../../src/plugins/plugin-api.mjs').PluginAPI} api
 */
export async function activate(api) {
    console.log(`[hello-world] Plugin activated!`);

    // ── Register a custom tool ──────────────────────────────────────────
    api.tools.register({
        useOriginalName: true,
        name: 'greet',
        description: 'Say hello from the hello-world plugin',
        parameters: {
            type: 'object',
            properties: {
                name: { type: 'string', description: 'Name to greet' }
            },
            required: ['name']
        },
        handler: async (args) => {
            const greeting = `Hello, ${args.name}! 👋 This greeting was generated by the hello-world plugin.`;
            
            // Emit an event other plugins can listen to
            api.events.emit('greeted', { name: args.name, greeting });
            
            // Store the greeting count
            const count = (await api.storage.get('greetCount')) || 0;
            await api.storage.set('greetCount', count + 1);
            
            return greeting;
        }
    });

    // ── Register a WebSocket handler ────────────────────────────────────
    api.ws.register('ping', async (data, ctx) => {
        ctx.ws.send(JSON.stringify({
            type: 'plugin:hello-world:pong',
            payload: { 
                message: 'Pong from hello-world plugin!',
                timestamp: new Date().toISOString()
            }
        }));
    });

    // ── Listen for system events ────────────────────────────────────────
    api.events.onSystem('chat:message', (data) => {
        console.log(`[hello-world] Chat message received:`, data?.content?.substring(0, 50));
    });

    // ── Use settings ────────────────────────────────────────────────────
    const welcomeMessage = await api.settings.get('welcomeMessage');
    if (!welcomeMessage) {
        await api.settings.set('welcomeMessage', 'Welcome to the hello-world plugin!');
    }

    console.log(`[hello-world] Initialization complete. Welcome: ${welcomeMessage || 'Welcome to the hello-world plugin!'}`);
}

/**
 * Called when the plugin is deactivated.
 * @param {import('../../src/plugins/plugin-api.mjs').PluginAPI} api
 */
export async function deactivate(api) {
    console.log(`[hello-world] Plugin deactivated. Goodbye!`);
    // Note: The plugin system automatically cleans up registered tools, WS handlers,
    // and event listeners — no manual cleanup needed here.
}
